# Generated by Django 3.2.7 on 2021-09-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='email'),
        ),
    ]
